version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
      # Jetpack libraries are usually released on each second Wednesday
      day: "thursday"
    registries: "*"
    labels:
      - "dependencies"
    open-pull-requests-limit: 10
