name: Publish to Github Packages
on:
  push:
    tags:
      - v*
jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: 11

      - name: Setup the environment
        run: |
          sudo pip3 install meson==0.58.2
          sudo apt-get install nasm ninja-build

      - name: Assembling the ffmpeg-android-maker
        run: ffmpeg-android-maker/ffmpeg-android-maker.sh -dav1d
        env:
          ANDROID_SDK_HOME: $ANDROID_HOME

      - name: Building the library and publishing it
        run: ./gradlew publish
        env:
          USERNAME: ${{ github.actor }}
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SIGNING_KEY_ID: ${{ secrets.SIGNING_KEY_ID }}
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
