name: Publish to Maven Central (SNAPSHOT)
on:
  push:
    branches:
      - develop
jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: 11

      - name: Setup the environment
        run: |
          sudo pip3 install meson==0.58.2
          sudo apt-get install nasm ninja-build

      - name: Assembling the ffmpeg-android-maker
        run: ffmpeg-android-maker/ffmpeg-android-maker.sh -dav1d
        env:
          ANDROID_SDK_HOME: $ANDROID_HOME
          ANDROID_NDK_HOME: $ANDROID_NDK_LATEST_HOME

      - name: Building the library, preparing sources and docs
        run: ./gradlew assembleRelease androidSourcesJar javadocJar

      - name: Pushing the library to Maven Central (SNAPSHOT)
        run: ./gradlew publishReleasePublicationToSonatypeRepository --max-workers 1
        env:
          SIGNING_KEY_ID: ${{ secrets.SIGNING_KEY_ID }}
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          SONATYPE_STAGING_PROFILE_ID: ${{ secrets.SONATYPE_STAGING_PROFILE_ID }}
          VERSION_SUFFIX: -SNAPSHOT