name: Publish to Maven Central
on:
  release:
    types: [ released ]
jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Gradle Wrapper Validation
        uses: gradle/wrapper-validation-action@v2

      - name: Overriding gradle.properties for CI
        run: mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Setup the environment
        run: |
          sudo pip3 install meson==1.4.0
          sudo apt-get install nasm ninja-build

      - name: Assembling the ffmpeg-android-maker
        run: |
          export ANDROID_SDK_HOME=$ANDROID_HOME
          export ANDROID_NDK_HOME=$ANDROID_NDK_LATEST_HOME
          ./ffmpeg-android-maker/ffmpeg-android-maker.sh -dav1d

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Building
        run: ./gradlew :media-file:assembleRelease

      - name: Testing
        run: ./gradlew :media-file:pixel2api34ReleaseAndroidTest

      - name: Publishing the library to Maven Central
        run: ./gradlew publishReleasePublicationToSonatypeRepository closeAndReleaseSonatypeStagingRepository --max-workers 1
        env:
          SIGNING_KEY_ID: ${{ secrets.SIGNING_KEY_ID }}
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          SONATYPE_STAGING_PROFILE_ID: ${{ secrets.SONATYPE_STAGING_PROFILE_ID }}
